name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Carthage checkout
      run: carthage update --no-build
#     - name: Run tests
#       run: swift test -v
