name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: check directory
      id: hi
      run: |
        cd CatalystTestProject \n
        carthage update --no-build
  
#       working-directory: ./../CatalystTestProject
#       shell: bash
    

      

