name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: check directory
      id: hi
      run: |
        cd CatalystTestProject \n
        carthage update --no-build
    - uses: actions/checkout@v2
    - name:  modify project
      id: hihi
      run: ./CatalystTestProject/scripts/modify.sh
    - name: carthage build
      id: hihihi
      run: |
        cd CatalystTestProject \n
        carthage update
    - name: carthage commit
      id: hihihihi
      run: |
        git add CatalystTestProject/Carthage/*
        git commit -m "add Carthage"
        git push origin master
#       working-directory: ./../CatalystTestProject
#       shell: bash
    

      

