name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: path refresh
      run: cd ../
    - name: Carthage checkout
      run: carthage update --no-build
      

