name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Carthage checkout
      working-directory: ./../CatalystTestProject
      run: carthage update --no-build
      shell: bash
    

      

