name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: check directory
      run: ls
    - name: Carthage checkout
      run: carthage update --no-build
#       working-directory: ./../CatalystTestProject
#       shell: bash
    

      

